image:
  name: quay.io/<YOUR_QUAY_USER>/wildfly-kubernetes-example
  tag: latest
build:
  enabled: false # The build part is not needed since we have already built our application with the wildfly-maven-plugin plugin
deploy:
  replicas: 3
  route:
    enabled: false # the route can be enabled, but only for OpenShift clusters