apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  # kubectl get ingressclass/nginx -o=jsonpath='{.metadata.name}'
  ingressClassName: nginx
  rules:
    - host: example-app.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: example-app-http
                port:
                  number: 8080